/**
 * app/api/youtube/liked-videos/route.ts
 * 從 YouTube Data API v3 抓取使用者喜歡的音樂影片（前5筆）
 * 作為 Google 登入使用者的「音樂人格」資料來源
 */

import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function GET() {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.email) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const user = await prisma.user.findUnique({
      where: { email: session.user.email },
    });

    if (!user) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    // 從資料庫取得 Google 帳號的 access_token
    const googleAccount = await prisma.account.findFirst({
      where: { userId: user.id, provider: "google" },
    });

    if (!googleAccount?.access_token) {
      return NextResponse.json(
        { error: "Google 帳號未連結或缺少授權 Token，請重新登入" },
        { status: 401 }
      );
    }

    // 呼叫 YouTube Data API v3：取得喜歡的音樂類別影片 (videoCategoryId=10)
    // 先取得 liked videos（最多 25 筆）
    const likedRes = await fetch(
      "https://www.googleapis.com/youtube/v3/videos?myRating=like&videoCategoryId=10&part=snippet,contentDetails&maxResults=25&fields=items(id,snippet(title,channelTitle,description,thumbnails,publishedAt),contentDetails(duration))",
      {
        headers: {
          Authorization: `Bearer ${googleAccount.access_token}`,
        },
      }
    );

    if (!likedRes.ok) {
      const errData = await likedRes.json().catch(() => ({}));
      const errMsg = errData?.error?.message || likedRes.statusText;
      console.error(`❌ [YouTube API Liked Videos Fetch Error]: Status: ${likedRes.status}, Message: ${errMsg}`);

      // 若是 403，代表 YouTube Data API v3 尚未啟用
      if (likedRes.status === 403) {
        return NextResponse.json(
          {
            error:
              "YouTube Data API v3 尚未啟用。請至 Google Cloud Console 啟用此 API，再重新登入授權。",
            detail: errMsg,
          },
          { status: 403 }
        );
      }

      // 若是 401，access_token 過期，需要重新登入
      if (likedRes.status === 401) {
        return NextResponse.json(
          { error: "YouTube 授權已過期，請重新以 Google 登入" },
          { status: 401 }
        );
      }

      return NextResponse.json(
        { error: `YouTube API 回應錯誤: ${errMsg}` },
        { status: likedRes.status }
      );
    }

    const likedData = await likedRes.json();
    const items = likedData.items || [];

    if (items.length === 0) {
      return NextResponse.json(
        { error: "YouTube 喜歡清單中找不到任何音樂影片（videoCategoryId=10）。請先在 YouTube 上對一些音樂 MV 按讚！" },
        { status: 404 }
      );
    }

    // 將 ISO 8601 duration (e.g. "PT3M45S") 轉換成秒數
    function parseDuration(iso: string): number {
      const match = iso.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
      if (!match) return 0;
      const hours = parseInt(match[1] || "0");
      const minutes = parseInt(match[2] || "0");
      const seconds = parseInt(match[3] || "0");
      return hours * 3600 + minutes * 60 + seconds;
    }

    // ─── 過濾機制：鎖定正式發行的音樂（Art Tracks） ───
    // 1. 長度 >= 60 秒（排除 60 秒內的短影音 Shorts）
    // 2. 長度 <= 900 秒（15分鐘，排除超長 DJ 混音、直播或二創長片）
    // 3. 簡介與頻道特徵：必須包含 "Provided to YouTube by" 或 "Auto-generated by YouTube" 標記，或來自 "- Topic" 官方主題頻道
    const filteredItems = items.filter((item: any) => {
      const durationSec = parseDuration(item.contentDetails.duration);
      if (durationSec < 60 || durationSec > 900) return false;

      const description = item.snippet?.description || "";
      const channelTitle = item.snippet?.channelTitle || "";

      const isOfficialRelease =
        description.includes("Provided to YouTube by") ||
        description.includes("Auto-generated by YouTube") ||
        channelTitle.endsWith(" - Topic");

      return isOfficialRelease;
    });

    if (filteredItems.length === 0) {
      return NextResponse.json(
        { error: "未找到符合 YouTube 官方音樂發行特徵（包含 Provided to YouTube by）的歌曲。請確認您在 YouTube Music 喜歡的是官方發行版本！" },
        { status: 404 }
      );
    }

    // 取前 5 筆並格式化成與 Spotify Top Tracks 相容的格式
    const tracks = filteredItems.slice(0, 5).map((item: any) => ({
      youtubeId: item.id,
      title: item.snippet.title,
      artist: item.snippet.channelTitle, // YouTube 以頻道名稱當作藝人
      album: "YouTube Music",
      coverImg: item.snippet.thumbnails?.high?.url || item.snippet.thumbnails?.default?.url || null,
      duration: parseDuration(item.contentDetails.duration),
      previewUrl: null, // YouTube 無法直接提供 previewUrl
      url: `https://www.youtube.com/watch?v=${item.id}`,
    }));

    return NextResponse.json(tracks);
  } catch (error) {
    console.error("[YouTube Liked Videos Error]:", error);
    return NextResponse.json(
      { error: "伺服器錯誤", detail: String(error) },
      { status: 500 }
    );
  }
}
